### ISSUE TITLE
Frequent "Communications link failure during rollback()"

### ISSUE THREAD

**Issue by driesken** [lsc-project/lsc#122]
I've upgraded to the latest lsc (lsc-2.1.5-1) but I've been getting some errors lately causing syncing issues between LDAP and MySQL. I'm using the mysql-connector-java-8.0.19 connector. The only workaround is to restart the service.

I was wondering if I could do some tweaking with the JDBC parameters to resolve this? 

```xml
<sqlMapConfig>
  <settings lazyLoadingEnabled="true" cacheModelsEnabled="true" enhancementEnabled="true" maxRequests="512" maxSessions="128" maxTransactions="32"/>
  <transactionManager type="JDBC">
    <dataSource type="SIMPLE">
      <property value="com.mysql.cj.jdbc.Driver" name="JDBC.Driver"/>
      <property value="jdbc:mysql://localhost:3306/asterisk" name="JDBC.ConnectionURL"/>
      <property value="xxxxxxxxxxxxxxxx" name="JDBC.Username"/>
      <property value="xxxxxxxxxxxxxxxx" name="JDBC.Password"/>
      <property value="15" name="Pool.MaximumActiveConnections"/>
      <property value="15" name="Pool.MaximumIdleConnections"/>
      <property value="1000" name="Pool.MaximumWait"/>
    </dataSource>
  </transactionManager>
  <sqlMap url="file://${lsc.config}/sql-map-config.d/uzg_ldap2mariadb.xml"/>
</sqlMapConfig>
```
```
Apr 21 09:16:26 astp3 lsc: Apr 21 09:16:26 - WARN  - Error while looking for a specific entry with id=employeeNumber=34166,ou=persoon,dc=internal,dc=uzgent,dc=be (java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.)
Apr 21 09:16:26 astp3 lsc: Apr 21 09:16:26 - DEBUG - java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
Apr 21 09:16:26 astp3 lsc: java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
Apr 21 09:16:26 astp3 lsc: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.19.jar:8.0.19]
Apr 21 09:16:26 astp3 lsc: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
Apr 21 09:16:26 astp3 lsc: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.19.jar:8.0.19]
Apr 21 09:16:26 astp3 lsc: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.19.jar:8.0.19]
Apr 21 09:16:26 astp3 lsc: at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1848) ~[mysql-connector-java-8.0.19.jar:8.0.19]
Apr 21 09:16:26 astp3 lsc: at com.ibatis.common.jdbc.SimpleDataSource.popConnection(SimpleDataSource.java:629) ~[ibatis-sqlmap-2.3.4.726.jar:na]
Apr 21 09:16:26 astp3 lsc: at com.ibatis.common.jdbc.SimpleDataSource.getConnection(SimpleDataSource.java:222) ~[ibatis-sqlmap-2.3.4.726.jar:na]
Apr 21 09:16:26 astp3 lsc: at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTransaction.init(JdbcTransaction.java:48) ~[ibatis-sqlmap-2.3.4.726.jar:na]
Apr 21 09:16:26 astp3 lsc: at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:89) ~[ibatis-sqlmap-2.3.4.726.jar:na]
Apr 21 09:16:26 astp3 lsc: at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForList(MappedStatement.java:139) ~[ibatis-sqlmap-2.3.4.726.jar:na]
Apr 21 09:16:26 astp3 lsc: at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:567) ~[ibatis-sqlmap-2.3.4.726.jar:na]
Apr 21 09:16:26 astp3 lsc: at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:541) ~[ibatis-sqlmap-2.3.4.726.jar:na]
Apr 21 09:16:26 astp3 lsc: at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:118) ~[ibatis-sqlmap-2.3.4.726.jar:na]
Apr 21 09:16:26 astp3 lsc: at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForList(SqlMapClientImpl.java:94) ~[ibatis-sqlmap-2.3.4.726.jar:na]
Apr 21 09:16:26 astp3 lsc: at org.lsc.service.AbstractJdbcService.getBean(AbstractJdbcService.java:201) ~[lsc-core-2.1.5.jar:na]
Apr 21 09:16:26 astp3 lsc: at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:731) [lsc-core-2.1.5.jar:na]
Apr 21 09:16:26 astp3 lsc: at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:689) [lsc-core-2.1.5.jar:na]
Apr 21 09:16:26 astp3 lsc: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
Apr 21 09:16:26 astp3 lsc: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
Apr 21 09:16:26 astp3 lsc: at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Apr 21 09:16:26 astp3 lsc: Apr 21 09:16:26 - ERROR - Error while synchronizing ID {employeenumber=34166}: org.lsc.exception.LscServiceException: javax.naming.CommunicationException: Communications link failure during rollback(). Transaction resolution unknown.
Apr 21 09:16:26 astp3 lsc: Apr 21 09:16:26 - DEBUG - org.lsc.exception.LscServiceException: javax.naming.CommunicationException: Communications link failure during rollback(). Transaction resolution unknown.
Apr 21 09:16:26 astp3 lsc: org.lsc.exception.LscServiceException: javax.naming.CommunicationException: Communications link failure during rollback(). Transaction resolution unknown.
Apr 21 09:16:26 astp3 lsc: at org.lsc.service.AbstractJdbcService.getBean(AbstractJdbcService.java:231) ~[lsc-core-2.1.5.jar:na]
Apr 21 09:16:26 astp3 lsc: at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:731) [lsc-core-2.1.5.jar:na]
Apr 21 09:16:26 astp3 lsc: at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:689) [lsc-core-2.1.5.jar:na]
Apr 21 09:16:26 astp3 lsc: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
Apr 21 09:16:26 astp3 lsc: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
Apr 21 09:16:26 astp3 lsc: at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Apr 21 09:16:26 astp3 lsc: Caused by: javax.naming.CommunicationException: Communications link failure during rollback(). Transaction resolution unknown.
Apr 21 09:16:26 astp3 lsc: ... 6 common frames omitted
```

**Comment by coudot** [comment]
Could you provide the LSC configuration? Do you know how to reproduce this?

**Comment by davidcoutadeur** [comment]
No answer for 4 years, so I close the issue. Don't hesitate to reopen if you encounter the same issue on LSC 2.2
