### ISSUE TITLE
Support For Amazon Corretto

### ISSUE THREAD

**Issue by jonathanvdwatt** [lsc-project/lsc#146]
Hello,

Just a quick question: what's the support look like for Amazon Corretto? I'm trying to run LSC on Corretto but it's seems to perform quite badly. I only have around 8,000 groups to sync from OpenLDAP to AD but it's taken a whole day to sync like 7 minor groups. What I'm also seeing is that the sync thread (`GroupSync-18` in this case) seems perpetually stuck in either `PARK` or `WAITING`:

```
"GroupSync-18" #18 prio=5 os_prio=0 tid=0x00007f3f84008000 nid=0x40 waiting on condition [0x00007f3f9e104000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000071f6dcc90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.sun.jndi.ldap.LdapRequest.getReplyBer(LdapRequest.java:120)
	at com.sun.jndi.ldap.Connection.readReply(Connection.java:469)
	at com.sun.jndi.ldap.LdapClient.getSearchReply(LdapClient.java:638)
	at com.sun.jndi.ldap.LdapClient.search(LdapClient.java:561)
	at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:2013)
	at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1872)
	at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1797)
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:392)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:358)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:341)
	at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:267)
	at org.lsc.jndi.JndiServices.doGetDnList(JndiServices.java:764)
	at org.lsc.jndi.JndiServices.getDnList(JndiServices.java:734)
	at org.lsc.jndi.ScriptableJndiServices._search(ScriptableJndiServices.java:112)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.lsc.jndi.ScriptableObject.wrap(ScriptableObject.java:92)
	at org.lsc.jndi.ScriptableObject.wrapString(ScriptableObject.java:155)
	at org.lsc.jndi.ScriptableJndiServices.search(ScriptableJndiServices.java:107)
	at java.lang.invoke.LambdaForm$DMH/2074407503.invokeSpecial_L3_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/1788767906.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/1452126962.delegate(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/810254013.guard(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/1023967965.linkToCallSite(LambdaForm$MH)
	at jdk.nashorn.internal.scripts.Script$5$\^eval\_.:program(<eval>:23)
	at java.lang.invoke.LambdaForm$DMH/1804094807.invokeStatic_LL_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/2073034465.invokeExact_MT(LambdaForm$MH)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
	at org.lsc.utils.JScriptEvaluator.instanceEval(JScriptEvaluator.java:227)
	at org.lsc.utils.JScriptEvaluator.evalToObjectList(JScriptEvaluator.java:122)
	at org.lsc.utils.ScriptingEvaluator.evalToObjectList(ScriptingEvaluator.java:136)
	at org.lsc.beans.BeanComparator.getValuesToSet(BeanComparator.java:602)
	at org.lsc.beans.BeanComparator.getUpdatedObject(BeanComparator.java:284)
	at org.lsc.beans.BeanComparator.calculateModifications(BeanComparator.java:176)
	at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:763)
	at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:689)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by soisik** [comment]
Hi,

Could you show the script(s) you're running in your datasets for this task ? The stacktrace seems to be waiting for some input from a search in one of the directory from one of your dataset, could be a big search/slow network or a very big amount of search being done ?

Have you tried running it with another JVM ?

**Comment by coudot** [comment]
@jonathanvdwatt did you solved your issue?
