### ISSUE TITLE
User Update for member groups not working

### ISSUE THREAD

**Issue by GSACRD-TECH** [lsc-project/lsc#149]
Working with the Synchronisation of the users to the groups and the system fails.
Had to modify the example from groupOfUniqueMemers to groupOfMembers and used memberUid instead of uniqueMembers. 

When I run the group sync with the uniqueMembers it builds the groups and no errors. If I use memberUid I get this for each group.
```
May 10 15:40:19 - ERROR - Programmatic error
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_275]
	at org.lsc.jndi.ScriptableObject.wrap(ScriptableObject.java:92) [lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.ScriptableObject.wrapString(ScriptableObject.java:155) [lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.ScriptableJndiServices.attribute(ScriptableJndiServices.java:262) [lsc-core-2.1.5.jar:na]
	at jdk.nashorn.internal.scripts.Script$23$\^eval\_.:program(<eval>:13) [na:na]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637) [nashorn.jar:na]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) [nashorn.jar:na]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) [nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449) [nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406) [nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402) [nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155) [nashorn.jar:na]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) [na:1.8.0_275]
	at org.lsc.utils.JScriptEvaluator.instanceEval(JScriptEvaluator.java:227) [lsc-core-2.1.5.jar:na]
	at org.lsc.utils.JScriptEvaluator.evalToObjectList(JScriptEvaluator.java:122) [lsc-core-2.1.5.jar:na]
	at org.lsc.utils.ScriptingEvaluator.evalToObjectList(ScriptingEvaluator.java:136) [lsc-core-2.1.5.jar:na]
	at org.lsc.beans.BeanComparator.getValuesToSet(BeanComparator.java:602) [lsc-core-2.1.5.jar:na]
	at org.lsc.beans.BeanComparator.getUpdatedObject(BeanComparator.java:284) [lsc-core-2.1.5.jar:na]
	at org.lsc.beans.BeanComparator.calculateModifications(BeanComparator.java:176) [lsc-core-2.1.5.jar:na]
	at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:763) [lsc-core-2.1.5.jar:na]
	at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:689) [lsc-core-2.1.5.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_275]
Caused by: java.lang.RuntimeException: org.apache.directory.api.ldap.model.exception.LdapInvalidDnException: ERR_04202 A value is missing on some RDN
	at org.lsc.jndi.JndiServices.rewriteBase(JndiServices.java:659) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.JndiServices.doReadEntry(JndiServices.java:691) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.JndiServices.readEntry(JndiServices.java:666) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.ScriptableJndiServices._attr(ScriptableJndiServices.java:269) [lsc-core-2.1.5.jar:na]
	... 26 common frames omitted
Caused by: org.apache.directory.api.ldap.model.exception.LdapInvalidDnException: ERR_04202 A value is missing on some RDN
	at org.apache.directory.api.ldap.model.name.Dn.<init>(Dn.java:279) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
	at org.apache.directory.api.ldap.model.name.Dn.<init>(Dn.java:211) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
	at org.lsc.jndi.JndiServices.rewriteBase(JndiServices.java:647) ~[lsc-core-2.1.5.jar:na]
	... 29 common frames omitted
```
This is the updated user sync for groups
                      <string>
                                <![CDATA[rjs: 
                                var membersSrcDn = srcBean.getDatasetValuesById("memberUid");
                                var membersDstDn = [];
                                for  (var i=0; i<membersSrcDn.size(); i++) {
                                        var memberSrcDn = membersSrcDn.get(i);
                                var uid = "";
                                try {
                                        uid = srcLdap.attribute(memberSrcDn, "uid").get(0);
                                } catch(e) {
                                        continue;
                                }
                                var destDn = ldap.search("OU=Users,DC=gsacrd,DC=ab,DC=ca", "(sAMAccountName=" + uid + ")");
                                if (destDn.size() == 0 || destDn.size() > 1) {
                                        continue;
                                }
                                var destMemberDn = destDn.get(0) + "," +  ldap.getContextDn();
                                membersDstDn.push(destMemberDn);
                                }
                                membersDstDn
                                ]]>
                        </string>

Hoping to be pointed in the right direction.

**Comment by GSACRD-TECH** [comment]
here is the code correctly formatted
```
                      <string>
                                <![CDATA[rjs: 
                                var membersSrcDn = srcBean.getDatasetValuesById("memberUid");
                                var membersDstDn = [];
                                for  (var i=0; i<membersSrcDn.size(); i++) {
                                        var memberSrcDn = membersSrcDn.get(i);
                                var uid = "";
                                try {
                                        uid = srcLdap.attribute(memberSrcDn, "uid").get(0);
                                } catch(e) {
                                        continue;
                                }
                                var destDn = ldap.search("OU=Users,DC=gsacrd,DC=ab,DC=ca", "(sAMAccountName=" + uid + ")");
                                if (destDn.size() == 0 || destDn.size() > 1) {
                                        continue;
                                }
                                var destMemberDn = destDn.get(0) + "," +  ldap.getContextDn();
                                membersDstDn.push(destMemberDn);
                                }
                                membersDstDn
                                ]]>
                        </string>
```

**Comment by soisik** [comment]
Hi,

This code synchronizes members full DN. As memberUid attribute contains users' uid, not the full DN, you don't need to search for the uid attribute:

```
var membersSrcUid = srcBean.getDatasetValuesById("memberUid");
var membersDstDn = [];
for  (var i=0; i<membersSrcUid.size(); i++) {
  var uid = membersSrcUid.get(i);
  var destDn = ldap.search("OU=Users,DC=gsacrd,DC=ab,DC=ca", "(sAMAccountName=" + uid + ")");
```

**Comment by GSACRD-TECH** [comment]
Made Changes and worked my way through the updated script
```
                                <![CDATA[rjs: 
                                var membersSrcUid = srcBean.getDatasetValuesById("memberUid");
                                var membersDstDn = [];
                                for  (var i=0; i<membersSrcUid.size(); i++) {
                                        var uid = membersSrcUid.get(i);
                                        var destDn = ldap.search("OU=Users,DC=gsacrd,DC=ab,DC=ca", "(sAMAccountName=" + uid + ")");
                                        if (destDn.size() == 0 || destDn.size() > 1) {
                                                continue;
                                                }
                                                var destMemberDn = destDn.get(0) + "," +  ldap.getContextDn();
                                                membersDstDn.push(destMemberDn);
                                        }
                                        membersDstDn
                                ]]>
```
This is now what it looks like but getting this error. Which is a java reference I believe. 
```
ERROR - Fail to compute expression: 
                                rjs: 
                                var membersSrcUid = srcBean.getDatasetValuesById("memberUid");
                                var membersDstDn = [];
                                for  (var i=0; i<membersSrcUid.size(); i++) {
	                                var uid = membersSrcUid.get(i);
	                                var destDn = ldap.search("OU=Users,DC=gsacrd,DC=ab,DC=ca", "(sAMAccountName=" + uid + ")");
        	                        if (destDn.size() == 0 || destDn.size() > 1) {
                	                        continue;
                        	        }
                                var destMemberDn = destDn.get(0) + "," +  ldap.getContextDn();
                                membersDstDn.push(destMemberDn);
                                }
                                membersDstDn
                                
                         on id=cn=olp-staff,ou=google,ou=groups,o=gsacrd,c=ca
Reason: javax.script.ScriptException: TypeError: null has no such function "size" in <eval> at line number 12
May 11 14:15:45 - ERROR - Error while synchronizing ID {cn=olp-staff}: org.lsc.exception.LscServiceException: javax.script.ScriptException: TypeError: null has no such function "size" in <eval> at line number 12
```
You input is most welcome. 
Thank you in advance.

**Comment by soisik** [comment]
Hi,
The base is wrong in var `destDn = ldap.search("OU=Users,DC=gsacrd,DC=ab,DC=ca", "(sAMAccountName=" + uid + ")");` and the method returns `null`, you should remove the contextDN declared in your connection Url.
For example, if your connection url is:
`<url>ldap://ad.domain.org:389/DC=gsacrd,DC=ab,DC=ca</url>`
Then call the search function with only `OU=Users` as base:  `destDn = ldap.search("OU=Users", "(sAMAccountName=" + uid + ")");`

**Comment by GSACRD-TECH** [comment]
That corrected the size error but now get this
```
May 12 09:26:46 - INFO  - LSC configuration successfully loaded from /etc/lsc/
May 12 09:26:46 - INFO  - Connecting to LDAP server ldaps://ldap-ad-sync.gsacrd.ab.ca:636/CN=Users,DC=gsacrd,DC=ab,DC=ca as CN=sync read,CN=Users,DC=gsacrd,DC=ab,DC=ca
May 12 09:26:46 - WARN  - Your baseDn settings (DC=gsacrd,DC=ab,DC=ca) does not end with the LDAP naming context (CN=Users,DC=gsacrd,DC=ab,DC=ca). This is probably an error ! For LSC 1.X users, this is part of the changelog to 2.X.
May 12 09:26:46 - INFO  - Connecting to LDAP server ldap://ldap-test.gsacrd.ab.ca:389/o=gsacrd,c=ca as uid=syncread,ou=roles,o=gsacrd,c=ca
May 12 09:26:46 - WARN  - Your baseDn settings (DC=gsacrd,DC=ab,DC=ca) does not end with the LDAP naming context (CN=Users,DC=gsacrd,DC=ab,DC=ca). This is probably an error ! For LSC 1.X users, this is part of the changelog to 2.X.
May 12 09:26:46 - INFO  - Starting sync for syncGroups
May 12 09:26:46 - ERROR - Error while looking for (&(objectClass=User)(cn=lts-staff)) in DC=gsacrd,DC=ab,DC=ca: javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:
	'CN=Users,DC=gsacrd,DC=ab,DC=ca'
]; remaining name 'DC=gsacrd,DC=ab,DC=ca'
May 12 09:26:46 - ERROR - Error while synchronizing ID {cn=lts-staff}: org.lsc.exception.LscServiceException: javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:
	'CN=Users,DC=gsacrd,DC=ab,DC=ca'
]; remaining name 'DC=gsacrd,DC=ab,DC=ca'
May 12 09:26:46 - ERROR - All entries: 1, to modify entries: 0, successfully modified entries: 0, errors: 1

```
Tried to update to the DN for all request areas and still does not find the group?

**Comment by GSACRD-TECH** [comment]
Maybe it is something in the entire destination setting.
```
 <ldapDestinationService>
                        <name>group-dst-service</name>
                        <connection reference="ad-dst-conn" />
                        <baseDn>DC=gsacrd,DC=ab,DC=ca</baseDn>
                        <pivotAttributes>
                                <string>cn</string>
                        </pivotAttributes>
                        <fetchedAttributes>
                                <string>cn</string>
                                <string>sAMAccountName</string>
                                <string>description</string>
                                <string>member</string>
                                <string>objectClass</string>
                        </fetchedAttributes>
                        <getAllFilter><![CDATA[(&(objectClass=User)(!(cn=Domain*))(!(cn=Allowed RODC Password Replication Group))(!(cn=Cert Publishers))(!(cn=Denied RODC Password Replication Group))(!(cn=RAS an>
                        <getOneFilter><![CDATA[(&(objectClass=User)(cn={cn}))]]></getOneFilter>
                </ldapDestinationService>
                <propertiesBasedSyncOptions>
                        <mainIdentifier>"cn=" + srcBean.getDatasetFirstValueById("cn") + ",CN=User"</mainIdentifier>
                        <defaultDelimiter>;</defaultDelimiter>
                        <defaultPolicy>KEEP</defaultPolicy>
                        <conditions>
                                <create>true</create>
                                <update>true</update>
                                <delete>true</delete>
                                <changeId>true</changeId>
                        </conditions>
                        <dataset>
                                <name>objectClass</name>
                                <policy>KEEP</policy>
                                <createValues>
                                        <string>"group"</string>
                                        <string>"top"</string>
                                </createValues>
                        </dataset>
                        <dataset>
                                <name>cn</name>
                                <policy>KEEP</policy>
                                <createValues><string>"cn"</string></createValues>
                        </dataset>
                        <dataset>
                                <name>sAMAccountName</name>
                                <policy>KEEP</policy>
                                <createValues><string>"cn"</string></createValues>
                        </dataset>
                        <dataset>
                                <name>description</name>
                                <policy>KEEP</policy>
                                <createValues><string>"displayName"</string></createValues>
                        </dataset>
                        <dataset>
                                <name>member</name>
                                <policy>FORCE</policy>
                                <forceValues><string>
                                <![CDATA[rjs: 
                                var membersSrcUid = srcBean.getDatasetValuesById("memberUid");
                                var membersDstDn = [];
                                for  (var i=0; i<membersSrcUid.size(); i++) {
                                        var uid = membersSrcUid.get(i);
                                        var destDn = ldap.search("OU=User", "(sAMAccountName=" + uid + ")");
                                        if (destDn.size() == 0 || destDn.size() > 1) {
                                                continue;
                                                }
                                                var destMemberDn = destDn.get(0) + "," +  ldap.getContextDn();
                                                membersDstDn.push(destMemberDn);
                                        }
                                        membersDstDn]]>
                                </string></forceValues>
                        </dataset>
                </propertiesBasedSyncOptions>
```

**Comment by GSACRD-TECH** [comment]
I have tried everything and Active Directory in 2016 Server has Changed how it likes to talk. 
I can perform and ldapsearch with no conditions and get all groups and users. as soon as I add any type of condition i get the same error in ldapsearch. 
Will let you know if I figure it out.

**Comment by coudot** [comment]
Default user branch in AD is `cn=Users`

**Comment by GSACRD-TECH** [comment]
Oh I have tried that and it gives the same error that it cant find anything.

**Comment by GSACRD-TECH** [comment]
This ldapsearch does get me the specific group and all of the details
```
ldapsearch -x -W -h ldap-ad-sync.gsacrd.ab.ca -b "cn=users,dc=gsacrd,dc=ab,dc=ca" -D "cn=sync read,cn=users,dc=gsacrd,dc=ab,dc=ca" "(&(objectClass=group)(cn=lts-staff))"

```
This ldapsearch gets me this 
`ldapsearch -x -W -h ldap-ad-sync.gsacrd.ab.ca -b "cn=users,dc=gsacrd,dc=ab,dc=ca" -D "cn=sync read,cn=users,dc=gsacrd,dc=ab,dc=ca" "(&(objectClass=users)(cn=lts-staff))"
`
with this as the result
```
# extended LDIF
#
# LDAPv3
# base <cn=users,dc=gsacrd,dc=ab,dc=ca> with scope subtree
# filter: (&(objectClass=users)(cn=lts-staff))
# requesting: ALL
#

# search result
search: 2
result: 0 Success

# numResponses: 1
```

But the error I am getting is 
```
Error while looking for (&(objectClass=Users)(cn=lts-staff)) in DC=gsacrd,DC=ab,DC=ca: javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:
	'CN=Users,DC=gsacrd,DC=ab,DC=ca'

```
So Not sure what to be looking for to get the system to adapt?

**Comment by GSACRD-TECH** [comment]
Found the Issue it was on the connection string.

**Comment by GSACRD-TECH** [comment]
So that runs but does not update the group with the users?

**Comment by GSACRD-TECH** [comment]
Found that too.

**Comment by GSACRD-TECH** [comment]
Okay Very Close to having this working 
Getting 
```
May 12 11:23:38 - INFO  - Starting sync for syncGroups
May 12 11:23:39 - ERROR - Error while adding entry cn=lts-staff,CN=Users in directory :javax.naming.NameAlreadyBoundException: [LDAP: error code 68 - 00002071: UpdErr: DSID-030503C4, problem 6005 (ENTRY_EXISTS), data 0
]; remaining name 'cn=lts-staff,CN=Users'
May 12 11:23:39 - ERROR - Error while synchronizing ID cn=lts-staff,CN=Users: java.lang.Exception: Technical problem while applying modifications to the destination
# Wed May 12 11:23:39 MDT 2021
dn: cn=lts-staff,CN=Users
changetype: add
sAMAccountName: cn
member: CN=Chris  Robinson,CN=Users,DC=gsacrd,DC=ab,DC=ca
member: CN=Karl  Stevens,CN=Users,DC=gsacrd,DC=ab,DC=ca
member: CN=Michelle  Boddez,CN=Users,DC=gsacrd,DC=ab,DC=ca
member: CN=John  Viveiros,CN=Users,DC=gsacrd,DC=ab,DC=ca
member: CN=Test user,CN=Users,DC=gsacrd,DC=ab,DC=ca
member: CN=Karla Holt,CN=Users,DC=gsacrd,DC=ab,DC=ca
member: CN=Kenneth Haas,CN=Users,DC=gsacrd,DC=ab,DC=ca
member: CN=Peter Ward,CN=Users,DC=gsacrd,DC=ab,DC=ca
objectClass: group
objectClass: top
description: displayName
cn: lts-staff

May 12 11:23:39 - ERROR - All entries: 1, to modify entries: 1, successfully modified entries: 0, errors: 1
```

**Comment by soisik** [comment]
LSC doesn't find any matching entry and tries to create one.
Check your destination getOneFilter. It should have objectClass=group, since your are syncing groups.
```
<getOneFilter><![CDATA[(&(objectClass=User)(cn={cn}))]]></getOneFilter>
```

**Comment by GSACRD-TECH** [comment]
That allows the group to Sync but has not user members to add.
this is what I get when the objectClass=Group
```
May 12 11:34:57 - INFO  - Starting sync for syncGroups
May 12 11:34:57 - WARN  - WARNING: updating the RDN of the entry will cancel other modifications! Relaunch synchronization to complete update.
May 12 11:34:57 - INFO  - # Renaming object CN=lts-staff,CN=Users,DC=gsacrd,DC=ab,DC=ca for syncGroups
# Wed May 12 11:34:57 MDT 2021
dn: CN=lts-staff,CN=Users,DC=gsacrd,DC=ab,DC=ca
changetype: modrdn
newrdn: cn=lts-staff
deleteoldrdn: 1
newsuperior: CN=Users

May 12 11:34:57 - INFO  - All entries: 1, to modify entries: 1, successfully modified entries: 1, errors: 0
```

**Comment by GSACRD-TECH** [comment]
The only way the sync works if I delete the groups on the AD server Then I get group and all users.
What do I need to change to have this update when the group is updated.

**Comment by GSACRD-TECH** [comment]
What do I need to configure to make the system synchronise existing user and groups as the system does not unless the user or group is deleted.
