### ISSUE TITLE
"Can't find bundle for base name javax.xml.bind.Messages, locale en_US"

### ISSUE THREAD

**Issue by ssskk77777** [lsc-project/lsc#157]
Hi everyone,

I'm trying to run LSC on Debian 10.9.0 (Latest Version), with :
- lsc_2.1.5-1
- jdk-16.0.1
- java -version : **openjdk version "11.0.11" 2021-04-20**

When i'm trying to test my configuration i've got the following errors :   

Error: java.util.MissingResourceException: Can't find bundle for base name javax.xml.bind.Messages, locale en_US
java.util.MissingResourceException: Can't find bundle for base name javax.xml.bind.Messages, locale en_US
        at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857)
        at javax.xml.bind.Messages.format(Messages.java:36)
        at javax.xml.bind.Messages.format(Messages.java:21)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:151)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:299)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:372)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:337)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:244)
        at org.lsc.configuration.JaxbXmlConfigurationHelper.<init>(JaxbXmlConfigurationHelper.java:105)
        at org.lsc.Configuration.setUp(Configuration.java:482)
        at org.lsc.Configuration.setUp(Configuration.java:456)
        at org.lsc.Launcher.run(Launcher.java:205)
        at org.lsc.Launcher.launch(Launcher.java:158)
        at org.lsc.Launcher.main(Launcher.java:141)
Caused by: java.lang.ClassCastException: javax.xml.bind.Messages cannot be cast to ResourceBundle
        at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3201)
        at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1994)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1776)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1662)
        ... 16 more

How to fix it ?
Thanks :)

**Comment by soisik** [comment]
Hi,
LSC 2.1 supports up to java 8.
Support for java 11 will come with 2.2 that hasn't been released yet.
