### ISSUE TITLE
java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.

### ISSUE THREAD

**Issue by donggak** [lsc-project/lsc#185]
```
2022-04-18 17:10:20 [] [WARN ]: aurora - Connection software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl@613e18e5 marked as broken because of SQLSTATE(08007), ErrorCode(0)
java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[aws-mysql-jdbc-1.0.0.jar:na]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[aws-mysql-jdbc-1.0.0.jar:na]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[aws-mysql-jdbc-1.0.0.jar:na]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[aws-mysql-jdbc-1.0.0.jar:na]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1881) ~[aws-mysql-jdbc-1.0.0.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_322]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_322]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_322]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_322]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.lambda$invoke$0(ConnectionProxy.java:191) ~[aws-mysql-jdbc-1.0.0.jar:na]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.DefaultConnectionPlugin.execute(DefaultConnectionPlugin.java:75) ~[aws-mysql-jdbc-1.0.0.jar:na]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.NodeMonitoringConnectionPlugin.execute(NodeMonitoringConnectionPlugin.java:173) ~[aws-mysql-jdbc-1.0.0.jar:na]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.execute(FailoverConnectionPlugin.java:244) ~[aws-mysql-jdbc-1.0.0.jar:na]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.ConnectionPluginManager.execute(ConnectionPluginManager.java:133) ~[aws-mysql-jdbc-1.0.0.jar:na]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.invoke(ConnectionProxy.java:188) ~[aws-mysql-jdbc-1.0.0.jar:na]
        at com.sun.proxy.$Proxy127.rollback(Unknown Source) ~[na:na]
        at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:370) ~[HikariCP-3.2.0.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java) [HikariCP-3.2.0.jar:na]
        at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:116) [hibernate-core-5.3.10.Final.jar:5.3.10.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.rollback(JdbcResourceLocalTransactionCoordinatorImpl.java:294) [hibernate-core-5.3.10.Final.ja
        at org.hibernate.engine.transaction.internal.TransactionImpl.rollback(TransactionImpl.java:145) [hibernate-core-5.3.10.Final.jar:5.3.10.Final]
        at org.springframework.orm.jpa.JpaTransactionManager.doRollback(JpaTransactionManager.java:559) [spring-orm-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:838) [spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:812) [spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.completeTransactionAfterThrowing(TransactionAspectSupport.java:552) [spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:299) [spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) [spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at com.sktelecom.smp.batch.job.service.ZSMPBSCM00010Service$$EnhancerBySpringCGLIB$$371cf562.batchPoprEqpStc(<generated>) [app/:na]
        at com.sktelecom.smp.batch.job.execute.ZSMPBSCM00010.executeInternal(ZSMPBSCM00010.java:91) [app/:na]
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75) [spring-context-support-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.1.jar:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.1.jar:na]
2022-04-18 17:10:20 [] [DEBUG]: aurora - Closing connection software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl@613e18e5: (connection is broken)
2022-04-18 17:10:20 [] [ERROR]: Application exception overridden by rollback exception
org.springframework.dao.RecoverableDataAccessException:
### Error updating database.  Cause: java.sql.SQLRecoverableException: No more data to read from socket
```

--> Customer Issue
I am using aws-mysql-jdbc 1.0.0, and the above error occurs.
However, no error occurs in mariadb-java-client (version 2.3.0).
My database is using Aurora MySQL. Can I use mariadb-java-client (version 2.3.0) when considering Aurora Mysql upgrade or failover?

**Comment by coudot** [comment]
Did you found a solution?

**Comment by donggak** [comment]
https://github.com/awslabs/aws-mysql-jdbc/issues/203 It overlapped with this, so I closed it.
