### ISSUE TITLE
java.lang.NullPointerException in JNDI service as source

### ISSUE THREAD

**Issue by kadogo** [lsc-project/lsc#192]
Hello I get that error after about 1h with 10 threads.

I do openlap (jndi) -> fusiondirectory (api).
I cannot reproduce the error if I use the shell ldap wrapper instead.

Changing the amount of threads only make a bit further but it still fail in the same way.

```
Jul 19 19:29:01 - ERROR - Error while synchronizing ID {uid=test-984}: java.lang.NullPointerException
Jul 19 19:29:01 - DEBUG - java.lang.NullPointerException
java.lang.NullPointerException: null
	at org.lsc.jndi.JndiServices.doGetEntry(JndiServices.java:589)
	at org.lsc.jndi.JndiServices.getEntry(JndiServices.java:550)
	at org.lsc.jndi.JndiServices.getEntry(JndiServices.java:528)
	at org.lsc.jndi.AbstractSimpleJndiService.get(AbstractSimpleJndiService.java:258)
	at org.lsc.jndi.SimpleJndiSrcService.getBean(SimpleJndiSrcService.java:152)
	at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:692)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I can provide two virtual machine if needed, one for the openldap source and the other one with my LSC install and fusiondirectory.

I add the version of my Adopt OpenJDK package

```
# apt-cache policy adoptopenjdk-8-hotspot-jre 
adoptopenjdk-8-hotspot-jre:
  Installed: 8u265-b01-3
  Candidate: 8u292-b10-3
  Version table:
     8u292-b10-3 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     8u282-b08-3 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     8u275-b01-3 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     8u272-b10-3 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
 *** 8u265-b01-3 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
        100 /var/lib/dpkg/status
     8u265-b01-2 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     8u262-b10-2 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     8u252-b09-2 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     8u242-b08-2 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     8u232-b09-2 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     8u222-b10-2 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     8u212-b04-2 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
     8u212-b03-1 500
        500 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster/main amd64 Packages
```

Cheers

**Comment by coudot** [comment]
See https://lsc-project.org/documentation/latest/upgrade#long_task

Try to set -i option with a duration that is higher than the duration of your sync

**Comment by kadogo** [comment]
Hello @coudot 

It worked with the -i option, thanks.
What the reason for that behavior?
Also I didn't reproduce that with the executable plugin it means that it's specifically to the JNDI service?

**Comment by coudot** [comment]
As written in upgrade notes, in LSC 2.1 we now close connections at the end of the task. In executable connections are managed in your scripts, LSC can't close them.

**Comment by coudot** [comment]
If you don't configure -i option, the connections will be closed after 1h. This is the intended behavior.
