### ISSUE TITLE
NullPointerException LDAP to SQL application

### ISSUE THREAD

**Issue by force-pc** [lsc-project/lsc#20]
Hi,

I'm having an issue with LSC. Basically my goal is to translate an LDAP directory in a MySQL database.
I configured  two connections, the first one for LDAP, the second one for the database.
Then I added a ldapSourceService and databaseDestinationService.

I know that my LDAP server is running and credentials are correct because if I put a wrong password, lsc will stop and tell me "Invalid credentials".
I'm currently able to browse my LDAP database using an external tool (JXplorer) using the following informations:
Host: 192.168.0.50
Port: 1389
Protocol: V3
Base DN: ou=people
Authentication: User + Password (no SSL)

The LDAP server is [Davmail](http://davmail.sourceforge.net/) which is basically a Microsotf Exchange to IMAP / SMTP / LDAP gateway.

When I launch lsc, I have the following log:
```
D:\lsc-2.1.4\bin>lsc.bat -f ../etc/ldap2sql -s all
Jun 26 12:38:16 - INFO  - Logging configuration successfully loaded from D:\lsc-2.1.4\bin\..\etc\ldap2sql\logback.xml
Jun 26 12:38:16 - INFO  - LSC configuration successfully loaded from D:\lsc-2.1.4\bin\..\etc\ldap2sql\
Jun 26 12:38:16 - DEBUG - Reading sql-map-config.xml from file:/D:/lsc-2.1.4/bin/../etc/ldap2sql/sql-map-config.xml
Jun 26 12:38:17 - INFO  - Connecting to LDAP server ldap://192.168.0.50:1389 as user@domain.com
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.18060.0.0.1
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.18060.0.0.1
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.7
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.7
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.2
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.2
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 1.2.840.113556.1.4.319
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 1.2.840.113556.1.4.319
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.3
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.3
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.10.1
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.10.1
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.18060.0.0.1
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.18060.0.0.1
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.7
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.7
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.2
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.2
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 1.2.840.113556.1.4.319
Jun 26 12:38:19 - INFO  - Registered pre-bundled control factory: 1.2.840.113556.1.4.319
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.3
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.3
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.10.1
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.10.1
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.42.2.27.8.5.1
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.42.2.27.8.5.1
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.9.1.3
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.9.1.3
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.9.1.4
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.9.1.4
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.9.1.1
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.9.1.1
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.9.1.2
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.3.6.1.4.1.4203.1.9.1.2
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.2.840.113556.1.4.473
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.2.840.113556.1.4.473
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.2.840.113556.1.4.474
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.2.840.113556.1.4.474
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.2.840.113556.1.4.841
Jun 26 12:38:20 - INFO  - Registered pre-bundled control factory: 1.2.840.113556.1.4.841
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.1.8
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.1.8
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.8
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.8
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.3
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.3
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.6
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.6
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.5
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.5
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.4203.1.11.1
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.4203.1.11.1
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.4203.1.11.3
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.4203.1.11.3
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.1466.20037
Jun 26 12:38:20 - INFO  - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.1466.20037
Jun 26 12:38:20 - ERROR - org.lsc.exception.LscConfigurationException: Configuration exception: null
Jun 26 12:38:20 - DEBUG - org.lsc.exception.LscConfigurationException: Configuration exception: null
org.lsc.exception.LscConfigurationException: Configuration exception: null
        at org.lsc.Task.<init>(Task.java:148) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.SimpleSynchronize.init(SimpleSynchronize.java:104) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.SimpleSynchronize.launch(SimpleSynchronize.java:154) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.run(Launcher.java:223) [lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.launch(Launcher.java:158) [lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.main(Launcher.java:141) [lsc-core-2.1.4.jar:na]
Caused by: java.lang.NullPointerException: null
        at org.lsc.jndi.JndiServices.getContextDn(JndiServices.java:1201) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.jndi.AbstractSimpleJndiService.<init>(AbstractSimpleJndiService.java:177) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.jndi.SimpleJndiSrcService.<init>(SimpleJndiSrcService.java:116) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.jndi.PullableJndiSrcService.<init>(PullableJndiSrcService.java:109) ~[lsc-core-2.1.4.jar:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_131]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_131]
        at org.lsc.Task.<init>(Task.java:143) ~[lsc-core-2.1.4.jar:na]
        ... 5 common frames omitted
```

Here is the content of my lsc.xml file:

```
<?xml version="1.0" ?>
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">

  <connections>
    <ldapConnection>
      <name>ldap-src-conn</name>
      <url>ldap://192.168.0.50:1389</url>
      <username>user@domain.com</username>
      <password>mypassword</password>
      <authentication>SIMPLE</authentication>
      <referral>IGNORE</referral>
      <derefAliases>NEVER</derefAliases>
      <version>VERSION_3</version>
      <pageSize>-1</pageSize>
      <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>
      <tlsActivated>false</tlsActivated>
	  <saslMutualAuthentication>false</saslMutualAuthentication>
    </ldapConnection>
	
    <databaseConnection>
      <name>jdbc-dst-conn</name>
      <url>jdbc:postgresql://192.168.0.50:3306/asterisk_outlook_directory</url>
      <username>asterisk</username>
      <password>asterisk_pwd</password>
      <driver>org.hsqldb.jdbcDriver</driver>
    </databaseConnection>
  </connections>

  <tasks>
    <task>
      <name>MySyncTask</name>
      <bean>org.lsc.beans.SimpleBean</bean>
      <ldapSourceService>
        <name>ldap-src-service</name>
        <connection reference="ldap-src-conn" />
        <baseDn>ou=people</baseDn>
        <pivotAttributes>
          <string>uid</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>cn</string>
          <string>givenname</string>
          <string>sn</string>
          <string>objectClass</string>
          <string>uid</string>
          <string>mail</string>
          <string>mobile</string>
          <string>homephone</string>
          <string>telephonenumber</string>
        </fetchedAttributes>
        <getAllFilter>(&amp;(objectClass=inetorgperson)(uid=*))</getAllFilter>
        <getOneFilter>(&amp;(objectClass=inetorgperson)(uid={uid}))</getOneFilter>
        <cleanFilter>(&amp;(objectClass=inetorgperson)(uid={uid}))</cleanFilter>
      </ldapSourceService>
	  
      <databaseDestinationService>
        <name>jdbc-dst-service</name>
        <connection reference="jdbc-dst-conn" />
        <requestNameForList>getInetOrgPersonList</requestNameForList>
        <requestNameForObject>getInetOrgPerson</requestNameForObject>
        <requestsNameForInsert><string>insertInetOrgPerson</string></requestsNameForInsert>
       	<requestsNameForUpdate><string>updateInetOrgPerson</string></requestsNameForUpdate>
       	<requestsNameForDelete><string>deleteInetOrgPerson</string></requestsNameForDelete>
      </databaseDestinationService>
	  
    <propertiesBasedSyncOptions>
        <mainIdentifier>"uid="+srcBean.getDatasetFirstValueById("uid")</mainIdentifier>
        <defaultDelimiter>;</defaultDelimiter>
        <defaultPolicy>FORCE</defaultPolicy>
        <conditions>
            <changeId>false</changeId>
        </conditions>
      </propertiesBasedSyncOptions>
    </task>
  </tasks>

</lsc>

```

Here is my InetOrgPerson.xml file
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE sqlMap PUBLIC "-//iBATIS.com//DTD SQL Map 2.0//EN" "http://www.ibatis.com/dtd/sql-map-2.dtd">

<sqlMap namespace="InetOrgPerson">

	<insert id="insertInetOrgPerson" parameterClass="java.util.Map">
			INSERT INTO inetorgperson
					( uid, sn, givenname, cn, mail, address, mobile, homephone, telephonenumber)
					VALUES ( #uid#, #sn#, #givenname#, #cn#, #mail#, #address#, #mobile#, #homephone#, #telephonenumber# )
	</insert>
	
	<update id="updateInetOrgPerson" parameterClass="java.util.Map">
			UPDATE inetorgperson
					SET , sn = #sn# , givenname = #givenname#, cn = #cn#, mail = #mail#, address = #address#, mobile = #mobile#, homephone = #homephone#, telephonenumber = #telephonenumber#
					WHERE id = #uid#
	</update>
	
	<delete id="deleteInetOrgPerson" parameterClass="java.util.Map">
			DELETE FROM inetorgperson
					WHERE id = #uid#
	</delete>
	
	<select id="getInetOrgPerson" resultClass="java.util.HashMap"
			parameterClass="java.util.Map">
	  SELECT uid as uid,
			 lastname as sn,
			 firstname as givenName,
			 name as cn,
			 email as mail,
			 address as address,
			 mobilephone as mobile,
			 homephone as homephone,
			 workphone as telephonenumber
	  FROM inetorgperson
	  WHERE uid = #uid#
	</select>

	<select id="getInetOrgPersonList" resultClass="java.util.HashMap">
	  SELECT uid as uid
	  FROM inetorgperson
	</select>

	<select id="getInetOrgPersonClean" resultClass="java.util.HashMap"
			parameterClass="java.util.Map">
	  SELECT uid as uid
	  FROM inetorgperson
	  WHERE uid = #uid#
	</select>

</sqlMap>
```

My sql-map-config.xml file is the default one, I just uncommented the line
`<sqlMap url="file://${lsc.config}/sql-map-config.d/InetOrgPerson.xml"/>`

There may be some errors in InetOrgPerson.xml but I can't debug further because it seems that I'm stuck on the LDAP connection.

Thank you for any help!

**Comment by coudot** [comment]
You seem to use an HSQLDB JDBC driver to access a PostGreSQL database, which should not work. Try to install a postgresql jdbc driver in LSC lib/ directory and use it in configuration

**Comment by force-pc** [comment]
Hi,
Thanks for your answer. I downloaded https://jdbc.postgresql.org/download/postgresql-42.1.1.jar and placed it into lib directory.
In the databaseConnection section, I put `<driver>org.postgresql.Driver</driver>` but same error message with same execution stack. :-(

**Comment by coudot** [comment]
The error seems to be:
```
Caused by: java.lang.NullPointerException: null
        at org.lsc.jndi.JndiServices.getContextDn(JndiServices.java:1201) ~[lsc-core-2.1.4.jar:na]
```

You need to define a context in LDAP URL, like this:
```
      <url>ldap://localhost/dc=savoirfairelinux,dc=net</url>
```

And also the base DN in LDAP src service must be the full DN of the branch, 
for example:
```
        <baseDn>ou=groups,dc=savoirfairelinux,dc=net</baseDn>
```

**Comment by force-pc** [comment]
Thanks, I was confused because my LDAP database doesn't have Domain Component (dc).
The working URL is: `<url>ldap://localhost:1389/ou=people/url>` and BaseDN is `<baseDn>ou=people</baseDn>`.
There was also some other errors in the file and in InetOrgPerson.xml. I post here the full working configuration, maybe it will help someone in the future.
I also had to limit the number of threads because the LDAP server (Davmail) was replying timeouts...

lsc.xml
```
<?xml version="1.0" ?>
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">

  <connections>
    <ldapConnection>
      <name>ldap-src-conn</name>
      <url>ldap://localhost:1389/ou=people</url>
      <username>user@domain.com</username>
      <password>password</password>
      <authentication>SIMPLE</authentication>
      <referral>IGNORE</referral>
      <derefAliases>NEVER</derefAliases>
      <version>VERSION_3</version>
      <pageSize>-1</pageSize>
      <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>
      <tlsActivated>false</tlsActivated>
      <saslMutualAuthentication>false</saslMutualAuthentication>
    </ldapConnection>
    
    <databaseConnection>
      <name>jdbc-dst-conn</name>
      <url>jdbc:mysql://localhost:3306/asterisk_outlook_directory</url>
      <username>asterisk</username>
      <password>asterisk_pwd</password>
      <driver>com.mysql.jdbc.Driver</driver>
    </databaseConnection>
  </connections>

  <tasks>
    <task>
      <name>LdapToMySqlTask</name>
      <bean>org.lsc.beans.SimpleBean</bean>
      <ldapSourceService>
        <name>ldap-src-service</name>
        <connection reference="ldap-src-conn" />
        <baseDn>ou=people</baseDn>
        <pivotAttributes>
          <string>uid</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>cn</string>
          <string>givenname</string>
          <string>sn</string>
          <string>objectClass</string>
          <string>uid</string>
          <string>mail</string>
          <string>address</string>
          <string>mobile</string>
          <string>homephone</string>
          <string>telephonenumber</string>
        </fetchedAttributes>
        <getAllFilter>(&amp;(objectClass=inetorgperson)(uid=*))</getAllFilter>
        <getOneFilter>(&amp;(objectClass=inetorgperson)(uid={uid}))</getOneFilter>
        <cleanFilter>(&amp;(objectClass=inetorgperson)(uid={uid}))</cleanFilter>
      </ldapSourceService>
      
      <databaseDestinationService>
        <name>jdbc-dst-service</name>
        <connection reference="jdbc-dst-conn" />
        <requestNameForList>getInetOrgPersonList</requestNameForList>
        <requestNameForObject>getInetOrgPerson</requestNameForObject>
        <requestsNameForInsert><string>insertInetOrgPerson</string></requestsNameForInsert>
        <requestsNameForUpdate><string>updateInetOrgPerson</string></requestsNameForUpdate>
        <requestsNameForDelete><string>deleteInetOrgPerson</string></requestsNameForDelete>
      </databaseDestinationService>
       
      <propertiesBasedSyncOptions>
        <mainIdentifier>"uid="+srcBean.getDatasetFirstValueById("uid")</mainIdentifier>
        <defaultDelimiter>;</defaultDelimiter>
        <defaultPolicy>FORCE</defaultPolicy>
        <conditions>
          <create>true</create>
          <update>true</update>
          <delete>true</delete>
          <changeId>false</changeId>
        </conditions>
      </propertiesBasedSyncOptions>
      
    </task>
  </tasks>
</lsc>
```

InetOrgPerson.xml
"users" is the name of my table in the database.
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE sqlMap PUBLIC "-//iBATIS.com//DTD SQL Map 2.0//EN" "http://www.ibatis.com/dtd/sql-map-2.dtd">

<sqlMap namespace="InetOrgPerson">

	<insert id="insertInetOrgPerson" parameterClass="java.util.Map">
			INSERT INTO users
					( uid, lastname, firstname, name, email, address, mobilephone, homephone, workphone)
					VALUES ( #uid#, #sn#, #givenName#, #cn#, #mail#, #address#, #mobile#, #homephone#, #telephonenumber# )
	</insert>
	
	<update id="updateInetOrgPerson" parameterClass="java.util.Map">
			UPDATE users
					SET , lastname = #sn# , firstname = #givenName#, name = #cn#, email = #mail#, address = #address#, mobilephone = #mobile#, homephone = #homephone#, workphone = #telephonenumber#
					WHERE uid = #uid#
	</update>
	
	<delete id="deleteInetOrgPerson" parameterClass="java.util.Map">
			DELETE FROM users
					WHERE uid = #uid#
	</delete>
	
	<select id="getInetOrgPerson" resultClass="java.util.HashMap"
			parameterClass="java.util.Map">
	  SELECT uid as uid,
			 lastname as sn,
			 firstname as givenName,
			 name as cn,
			 email as mail,
			 address as address,
			 mobilephone as mobile,
			 homephone as homephone,
			 workphone as telephonenumber
	  FROM users
	  WHERE uid = #uid#
	</select>

	<select id="getInetOrgPersonList" resultClass="java.util.HashMap">
	  SELECT uid as uid
	  FROM users
	</select>

	<select id="getInetOrgPersonClean" resultClass="java.util.HashMap"
			parameterClass="java.util.Map">
	  SELECT uid as uid
	  FROM users
	  WHERE uid = #uid#
	</select>

</sqlMap>
```

sql-map-config.xml as default with line `<sqlMap url="file://${lsc.config}/sql-map-config.d/InetOrgPerson.xml"/>` uncommented.

And finally the command-line used: `lsc -f /etc/lsc/ldap2sql -s all -c all -t 1`

**Comment by coudot** [comment]
Thanks for the feedback!
