### ISSUE TITLE
MySQL Source: "java.lang.NullPointerException"

### ISSUE THREAD

**Issue by mathieumd** [lsc-project/lsc#214]
I have an LSC job actually synchronizing from and AD and an LDAP into another LDAP. It's working well.

Now, I need to retrieve the corresponding telephone numbers from a MySQL database.

On my LSC server (Ubuntu), I installed `libmariadb-java`, added a symlink from `/usr/lib/lsc/mariadb-java-client.jar` to `/usr/share/java/mariadb-java-client.jar` (is it even necessary?), then configured LSC (see below).

But when I try it:

```bash
sudo -u lsc lsc -f /etc/lsc/myproject -s telephones -n
#...
avr. 18 17:07:31 - INFO  - LSC configuration successfully loaded from /etc/lsc/myproject/
#...
avr. 18 17:07:34 - DEBUG - Reading sql-map-config.xml from file:/etc/lsc/myproject/sql-map-config.xml
avr. 18 17:07:34 - INFO  - Starting sync for telephones
avr. 18 17:07:34 - ERROR - Error getting list of IDs in the source for task telephones
avr. 18 17:07:34 - DEBUG - java.lang.NullPointerException
java.lang.NullPointerException: null
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.endTransaction(SqlMapExecutorDelegate.java:734)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.endTransaction(SqlMapSessionImpl.java:176)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.endTransaction(SqlMapClientImpl.java:153)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.autoEndTransaction(SqlMapExecutorDelegate.java:835)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:574)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:541)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:118)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:122)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForList(SqlMapClientImpl.java:98)
        at org.lsc.service.AbstractJdbcService.getListPivots(AbstractJdbcService.java:159)
        at org.lsc.AbstractSynchronize.synchronize2Ldap(AbstractSynchronize.java:306)
        at org.lsc.SimpleSynchronize.launchTask(SimpleSynchronize.java:232)
        at org.lsc.SimpleSynchronize.launch(SimpleSynchronize.java:166)
        at org.lsc.Launcher.run(Launcher.java:223)
        at org.lsc.Launcher.launch(Launcher.java:158)
        at org.lsc.Launcher.main(Launcher.java:141)
```

I don't understand what is going wrong.

<details>
<summary>The file configurations:</summary>

`lsc.xml`:
```xml
<?xml version="1.0" ?>
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">
  <connections>
    <!-- ... -->
    <databaseConnection>
      <name>sql-src-annuaire</name>
      <url>jdbc:mariadb://dbsrv.example.com:3306/mydatabase</url>
      <username>mysqluser</username>
      <password>xxx</password>
      <driver>org.mariadb.jdbc.Driver</driver>
    </databaseConnection>
  </connections>
<!-- ... -->
    <task>
      <name>telephones</name>
      <bean>org.lsc.beans.SimpleBean</bean>
      <databaseSourceService>
        <name>sql-src-telephones</name>
        <connection reference="sql-src-annuaire"/>
        <requestNameForList>getAnnuairePersonList</requestNameForList>
        <requestNameForObject>getAnnuairePerson</requestNameForObject>
        <requestNameForClean>getAnnuairePersonClean</requestNameForClean>
      </databaseSourceService>
      <ldapDestinationService>
      <!-- ... -->
      </ldapDestinationService>

      <propertiesBasedSyncOptions>
        <mainIdentifier>srcBean.getDatasetFirstValueById("uid")</mainIdentifier>
        <defaultDelimiter>;</defaultDelimiter>
        <defaultPolicy>FORCE</defaultPolicy>

        <dataset>
          <name>telephoneNumber</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>srcBean.getDatasetFirstValueById("telephoneNumber")</string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
```

`sql-map-config.d/annuairePerson.xml`:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE sqlMap PUBLIC "-//iBATIS.com//DTD SQL Map 2.0//EN" "http://www.ibatis.com/dtd/sql-map-2.dtd">

<sqlMap namespace="annuairePerson">

  <select id="getAnnuairePersonList" resultClass="java.util.HashMap">
    SELECT UserId as uid
    FROM personne
  </select>

  <select id="getAnnuairePerson" resultClass="java.util.HashMap"
          parameterClass="java.util.Map">
    SELECT UserId as uid,
           Telephone as telephoneNumber,
           Portable as mobileTelephoneNumber
    FROM personne
    WHERE UserId = #uid#
  </select>

  <select id="getAnnuairePersonClean" resultClass="java.util.HashMap"
          parameterClass="java.util.Map">
    SELECT UserId as uid
    FROM personne
    WHERE UserId = #uid#
  </select>

</sqlMap>
```

and `sql-map-config.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMapConfig
  PUBLIC "-//ibatis.apache.org//DTD SQL Map Config 2.0//EN"
  "http://ibatis.apache.org/dtd/sql-map-config-2.dtd">

<sqlMapConfig>
  <sqlMap url="file://${lsc.config}/sql-map-config.d/annuairePerson.xml"/>
</sqlMapConfig>
```
</details>

**Comment by mathieumd** [comment]
Thanks Clément. Unfortunately, I replaced `#uid#` by `#userid#`, but it did not change anything:

```
...
avr. 21 09:11:23 - DEBUG - Reading sql-map-config.xml from file:/etc/lsc/ad2ldap/sql-map-config.xml
avr. 21 09:11:23 - INFO  - Starting sync for telephones
avr. 21 09:11:23 - ERROR - Error getting list of IDs in the source for task telephones
avr. 21 09:11:23 - DEBUG - java.lang.NullPointerException
java.lang.NullPointerException: null
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.endTransaction(SqlMapExecutorDelegate.java:734)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.endTransaction(SqlMapSessionImpl.java:176)
...
```

By the way, I do confirm that this SQL request does works:

```bash
mysql ... --execute "SELECT * FROM personne;" |head -1
UserId  Telephone       Portable        Email   Photo

mysql ... --execute "SELECT count(UserId) as uid FROM personne;"
+-----+
| uid |
+-----+
| 986 |
+-----+
```

**Comment by coudot** [comment]
Are there rows where userid is null? You can try to add a where clause like `WHERE UserId is not null` to be sure of that.

Try also #UserId# instead of #userid#, but I think iBatis wants to lowercase value

**Comment by mathieumd** [comment]
There is no row with a null `UserId`. But even adding `WHERE UserId is not null` to `getAnnuairePersonList` did not help.

`#UserId#` didn't neither.

**Comment by coudot** [comment]
I don't see what is missing. The error "Error getting list of IDs in the source" is triggered when no data is returned from the list request.
Could you get some logs on database side to see what is returned to LSC?

**Comment by mathieumd** [comment]
It looks like the request is not reaching the server. When I do a `mysql` by hand, it get logged in the MySQL's `general_log`, but when I run `lsc -n` it does not. Is there a way to check my JDBC driver installation and declaration in LSC?

**Comment by soisik** [comment]
What value do you have in `<driver>` in your connexion configuration in lsc.xml ? It seems you have the wrong driver.

**Comment by mathieumd** [comment]
`<driver>org.mariadb.jdbc.Driver</driver>`

I installed `libmariadb-java`, added a symlink from `/usr/lib/lsc/mariadb-java-client.jar` to `/usr/share/java/mariadb-java-client.jar`

**Comment by mathieumd** [comment]
I am so sorry! You are right Soisik!

Simply adding the missing `<transactionManager>` fix it.

I may have missed it because, in [the doc](https://lsc-project.org/doku.php/documentation/latest/configuration/database/persistence), I read *No need to understand*, and I guess I took it too literally... :-/

Thanks again, and sorry Clément for your wasted time... m(_ _)m
