### ISSUE TITLE
Issue with java version

### ISSUE THREAD

**Issue by keobr** [lsc-project/lsc#220]
Looks like lsc sync does not work correctly with latest java update (java-1.8.0-openjdk-1:1.8.0.362.b08-3.el8.x86_64) and TLS1.3
Works correctly with version java-1.8.0-openjdk-1.8.0.322.b06

**Comment by coudot** [comment]
More info would be become, logs, stack trace, etc.

**Comment by keobr** [comment]
1. java-1.8.0-openjdk-1:1.8.0.362.b08-3.el8.x86_64
![Screenshot from 2023-08-08 13-41-50](https://github.com/lsc-project/lsc/assets/47155091/a16a5f3d-8f7c-450e-af09-1a508cf53433)
lsc error: ERROR - org.lsc.exception.LscConfigurationException: Configuration exception: org.apache.directory.api.ldap.model.exception.LdapException: The response queue has been emptied, no response was found
2. java 1.8.0_322-b06 
![Screenshot from 2023-08-08 13-44-27](https://github.com/lsc-project/lsc/assets/47155091/c5188366-d7c7-4c8a-bba9-74005b9c4c5d)

**Comment by keobr** [comment]
Aug 09 05:50:12 - ERROR - Bind failed : timeout occurred
Aug 09 05:50:12 - ERROR - Bind failed : timeout occurred
Aug 09 05:50:12 - ERROR - The response queue has been emptied, no response was found.
org.apache.directory.api.ldap.model.exception.LdapException: TimeOut occurred
	at org.apache.directory.ldap.client.api.LdapNetworkConnection.bind(LdapNetworkConnection.java:1130)
	at org.apache.directory.ldap.client.api.AbstractLdapConnection.bind(AbstractLdapConnection.java:127)
	at org.apache.directory.ldap.client.api.AbstractLdapConnection.bind(AbstractLdapConnection.java:112)
	at org.lsc.service.SyncReplSourceService.getConnection(SyncReplSourceService.java:174)
	at org.lsc.service.SyncReplSourceService.<init>(SyncReplSourceService.java:145)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.lsc.Task.<init>(Task.java:143)
	at org.lsc.SimpleSynchronize.init(SimpleSynchronize.java:104)
	at org.lsc.SimpleSynchronize.launch(SimpleSynchronize.java:154)
	at org.lsc.Launcher.run(Launcher.java:223)
	at org.lsc.Launcher.launch(Launcher.java:158)
	at org.lsc.Launcher.main(Launcher.java:141)
Aug 09 05:50:12 - ERROR - The response queue has been emptied, no response was found.
org.apache.directory.api.ldap.model.exception.LdapException: TimeOut occurred
	at org.apache.directory.ldap.client.api.LdapNetworkConnection.bind(LdapNetworkConnection.java:1130)
	at org.apache.directory.ldap.client.api.AbstractLdapConnection.bind(AbstractLdapConnection.java:127)
	at org.apache.directory.ldap.client.api.AbstractLdapConnection.bind(AbstractLdapConnection.java:112)
	at org.lsc.service.SyncReplSourceService.getConnection(SyncReplSourceService.java:174)
	at org.lsc.service.SyncReplSourceService.<init>(SyncReplSourceService.java:145)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.lsc.Task.<init>(Task.java:143)
	at org.lsc.SimpleSynchronize.init(SimpleSynchronize.java:104)
	at org.lsc.SimpleSynchronize.launch(SimpleSynchronize.java:154)
	at org.lsc.Launcher.run(Launcher.java:223)
	at org.lsc.Launcher.launch(Launcher.java:158)
	at org.lsc.Launcher.main(Launcher.java:141)
Aug 09 05:50:12 - ERROR - org.lsc.exception.LscConfigurationException: Configuration exception: org.apache.directory.api.ldap.model.exception.LdapException: The response queue has been emptied, no response was found.
Aug 09 05:50:12 - DEBUG - org.lsc.exception.LscConfigurationException: Configuration exception: org.apache.directory.api.ldap.model.exception.LdapException: The response queue has been emptied, no response was found.
org.lsc.exception.LscConfigurationException: Configuration exception: org.apache.directory.api.ldap.model.exception.LdapException: The response queue has been emptied, no response was found.
	at org.lsc.Task.<init>(Task.java:148)
	at org.lsc.SimpleSynchronize.init(SimpleSynchronize.java:104)
	at org.lsc.SimpleSynchronize.launch(SimpleSynchronize.java:154)
	at org.lsc.Launcher.run(Launcher.java:223)
	at org.lsc.Launcher.launch(Launcher.java:158)
	at org.lsc.Launcher.main(Launcher.java:141)
Caused by: org.lsc.exception.LscServiceConfigurationException: org.apache.directory.api.ldap.model.exception.LdapException: The response queue has been emptied, no response was found.
	at org.lsc.service.SyncReplSourceService.getConnection(SyncReplSourceService.java:182)
	at org.lsc.service.SyncReplSourceService.<init>(SyncReplSourceService.java:145)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.lsc.Task.<init>(Task.java:143)
	... 5 common frames omitted
Caused by: org.apache.directory.api.ldap.model.exception.LdapException: The response queue has been emptied, no response was found.
	at org.apache.directory.ldap.client.api.LdapNetworkConnection.bind(LdapNetworkConnection.java:1158)
	at org.apache.directory.ldap.client.api.AbstractLdapConnection.bind(AbstractLdapConnection.java:127)
	at org.apache.directory.ldap.client.api.AbstractLdapConnection.bind(AbstractLdapConnection.java:112)
	at org.lsc.service.SyncReplSourceService.getConnection(SyncReplSourceService.java:174)
	... 11 common frames omitted
Caused by: org.apache.directory.api.ldap.model.exception.LdapException: TimeOut occurred
	at org.apache.directory.ldap.client.api.LdapNetworkConnection.bind(LdapNetworkConnection.java:1130)
	... 14 common frames omitted

**Comment by keobr** [comment]
I found a similar error: https://issues.apache.org/jira/browse/DIRAPI-381

**Comment by coudot** [comment]
So we should see if updating our dependencies is enough to fix this issue (see #106)

**Comment by keobr** [comment]
https://github.com/lsc-project/lsc/tree/github-204-upgrade has been builded and executed
works correctly with the latest version java
