### ISSUE TITLE
Sync failed - ERROR while synchronizing / Only a single record can be returned from a getObject request

### ISSUE THREAD

**Issue by Pitouflin** [lsc-project/lsc#224]
Hello everyone, I am trying to synchronize my contatc database with my ldap server. I already succeeded in accessing my database and connecting to my ldap server but when I try to synchronize, I have an error I can't resolve (yet) : 
`sept. 07 14:28:34 - ERROR - Error while synchronizing ID {cn=CN}: org.lsc.exception.LscServiceException: Only a single record can be returned from a getObject request ! For id=CN, there are 10632 records !`

I went and looked around to check if there was an already available solution I could use but nothing came out of it. 
Could you please help me ?

Here is the configuration I use (wrong adresses, users and passwords)

[contact.txt](https://github.com/lsc-project/lsc/files/12549735/contact.txt)
[lsc.txt](https://github.com/lsc-project/lsc/files/12549737/lsc.txt)

**Comment by coudot** [comment]
Hello,

your `getContact` query must return only one entry.

Try:
```

        <select id="getContact" resultClass="java.util.HashMap" parameterClass="java.util.Map">
                Select
                        'contact' objectClass,
                        "CN",
                        "SN",
                        "GIVENNAME",
                        "CN",
                        "MOBILE",
                        "OTHERTELEPHONE"
                        "COMPANY",
                        "POSTALADDRESS",
                        "TELEPHONENUMBER",
                        "PERSONALTITLE"
                FROM ldap_contacts WHERE CN={cn}
        </select>
```

**Comment by Pitouflin** [comment]
Updated getContact. I now have this error : 
`sept. 07 17:05:45 - WARN  - Error while looking for a specific entry with id=CN ({})
com.ibatis.common.jdbc.exception.NestedSQLException:
--- The error occurred in file:///etc/lsc//sql-map-config.d/Contact.xml.
--- The error occurred while applying a parameter map.
--- Check the getContact-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '}' at line 1
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForList(MappedStatement.java:139)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:567)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:541)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:118)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForList(SqlMapClientImpl.java:94)
        at org.lsc.service.AbstractJdbcService.getBean(AbstractJdbcService.java:201)
        at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:692)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '}' at line 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
        ... 10 common frames omitted
sept. 07 17:05:45 - ERROR - Error while synchronizing ID {cn=CN}: org.lsc.exception.LscServiceException: javax.naming.CommunicationException:
--- The error occurred in file:///etc/lsc//sql-map-config.d/Contact.xml.
--- The error occurred while applying a parameter map.
--- Check the getContact-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '}' at line 1
sept. 07 17:05:45 - ERROR - All entries: 1, to modify entries: 0, successfully modified entries: 0, errors: 1`

**Comment by Pitouflin** [comment]
updated it again, facing new problem now :
`sept. 07 17:37:24 - ERROR - Cannot synchronize entry CN: no matching object found in source with pivots {cn=CN}
sept. 07 17:37:24 - ERROR - All entries: 1, to modify entries: 0, successfully modified entries: 0, errors: 1`

**Comment by Pitouflin** [comment]
I will check, thank you for your quick responses

**Comment by Pitouflin** [comment]
I went and checked back to contact.xml and saw that the "filters" on the CN field were different in getContact : 
`<select id="getContact" resultClass="java.util.HashMap" parameterClass="java.util.Map">
                Select
                        'contact' objectClass,
                        "CN",
                        "SN",
                        "GIVENNAME",
                        "CN",
                        "MOBILE",
                        "OTHERTELEPHONE"
                        "COMPANY",
                        "POSTALADDRESS",
                        "TELEPHONENUMBER",
                        "PERSONALTITLE"
                FROM ldap_contacts WHERE CN=#cn#
        </select>`

and in checkContactForClean : 
`<select id="checkContactForClean" resultClass="java.util.HashMap" parameterClass="java.util.Map">
                SELECT
                "CN" AS CN
                FROM ldap_contacts
                WHERE "CN" LIKE #cn#
        </select>`
I tried to use the same filtering in both methods but nothing worked, however, I got different types of errors :
both using `"CN" LIKE #cn#` : `sept. 08 09:19:32 - ERROR - Error while synchronizing ID {cn=CN}: org.lsc.exception.LscServiceException: Only a single record can be returned from a getObject request ! For id=CN, there are 10638 records !`
both using `CN = #cn#` : `sept. 08 09:20:44 - ERROR - Cannot synchronize entry CN: no matching object found in source with pivots {cn=CN}`
I don't understand the difference between the two filters and why it gives me different errors, could you please explain it to me ?

**Comment by coudot** [comment]
See https://lsc-project.org/doku.php/documentation/latest/basics 

The cn value is taken from getContactList request and then used in getContact to return only one row

**Comment by Pitouflin** [comment]
I found the problem, in my contact.xml, I used "" to define the fields I was selecting, but when I ran the same request in my database, all it returned me was always the same value for each entry : 
![image](https://github.com/lsc-project/lsc/assets/99023646/10380d24-dccc-4794-b292-58a4ef119c63)
When I got rid of the "" I had a new type of error : 
`ERROR - Cannot synchronize entry placeholderName: no matching object found in source with pivots {cn=placeholderName&Number}`
for all entries, how can I solve it ?

**Comment by Pitouflin** [comment]
I don't really understand why getContactList manages to access the data in my database but getContact doesn't, can someone explain it to me ?

**Comment by coudot** [comment]
Did your try to use `LIKE` in the `WHERE` clause of getContact?

**Comment by Pitouflin** [comment]
Yes I did, however when I looked at var/log/syslog, it look like the connection to my database got aborted between getContactList and getContact. Since I noticed this I'm looking for a way to make both querries go through without getting aborted
