### ISSUE TITLE
Ldap2LdapSyncTest test execution failed

### ISSUE THREAD

**Issue by amottier** [lsc-project/lsc#225]
Hi,

I'm trying to build the project `master` branch using `OpenJDK Runtime Environment (Temurin)(build 1.8.0_382-b05)` with `Maven 3.9.4` on Debian 12.1 (limiting the test execution to the only one failing: `./mvnw -Popendj,jdk8 -Dtest=Ldap2LdapSyncTest clean package`) and all 3 tests of `Ldap2LdapSyncTest` failed:

```
[ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 4.249 s <<< FAILURE! - in org.lsc.Ldap2LdapSyncTest
[ERROR] org.lsc.Ldap2LdapSyncTest.testReadUserPasswordFromLdap  Time elapsed: 1.279 s  <<< FAILURE!
java.lang.AssertionError
        at org.lsc.Ldap2LdapSyncTest.testReadUserPasswordFromLdap(Ldap2LdapSyncTest.java:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[ERROR] org.lsc.Ldap2LdapSyncTest.testSyncLdap2Ldap  Time elapsed: 2.455 s  <<< FAILURE!
java.lang.AssertionError
        at org.lsc.Ldap2LdapSyncTest.checkSyncResultsCommon(Ldap2LdapSyncTest.java:245)
        at org.lsc.Ldap2LdapSyncTest.checkSyncResultsFirstPass(Ldap2LdapSyncTest.java:184)
        at org.lsc.Ldap2LdapSyncTest.testSyncLdap2Ldap(Ldap2LdapSyncTest.java:164)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[ERROR] org.lsc.Ldap2LdapSyncTest.testCleanLdap2Ldap  Time elapsed: 0.466 s  <<< FAILURE!
java.lang.AssertionError
        at org.lsc.Ldap2LdapSyncTest.testCleanLdap2Ldap(Ldap2LdapSyncTest.java:306)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```

It looks like that the synchronization didn't happen.

I would appreciate any suggestions to guide me in fixing those tests execution. Thanks.

**Comment by amottier** [comment]
I double checked and I don't have any running LDAP server.

Based on [`misc/build-runldap.xml`](https://github.com/lsc-project/lsc/blob/79a5f91f12f751837c67674c4a8917d037499ddf/misc/build-runldap.xml#L40) listening port of LDAP server for test is `33389` and I confirm (with `sudo ss -l -n -p`) that this port is not used (nor `389`, `636`)

**Comment by amottier** [comment]
I can confirm that now I'm able to successfully, thanks a lot @soisik :+1:
