### ISSUE TITLE
Problem with execution lsc connector

### ISSUE THREAD

**Issue by ccharkos33** [lsc-project/lsc#25]
Hello 

the program return a problem : 
command : /usr/bin/lsc -f /etc/lsc/openldap2ad -s all -c all -n
ERROR - Defined configuration location (/etc/lsc/openldap2ad/lsc.xml) points to a non existing LSC configured instance. LSC configuration loading will fail

Do you have any idea of ​​the problem ?

best regard

Clément

Ps : my english is very bad :( i am french ^^

**Comment by coudot** [comment]
It means there is no file lsc.xml in /etc/lsc/openldap2ad directory. Did you create it?

**Comment by ccharkos33** [comment]
The file lsc.xml exist in /etc/lsc/openldap2ad directory

**Comment by coudot** [comment]
Then check file permissions

**Comment by coudot** [comment]
Do you run lsc as root?

**Comment by ccharkos33** [comment]
yes

**Comment by coudot** [comment]
Check there is no security protection like SELinux that protect the file

**Comment by ccharkos33** [comment]
no selinux in debain 8

**Comment by coudot** [comment]
Try /usr/bin/lsc -f /etc/lsc/openldap2ad -v to just check the configuration

Try also /usr/bin/lsc -f /etc/lsc -v to check default provided configuration

**Comment by ccharkos33** [comment]
/usr/bin/lsc -f /etc/lsc/openldap2ad -v 

16:24:58,218 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:24:58,219 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/etc/lsc/logback.xml]
16:24:58,221 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
16:24:58,221 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/etc/lsc/logback.xml]
16:24:58,221 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/lib/lsc/lsc-core-2.1.4.jar!/logback.xml]
16:24:58,368 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:24:58,378 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:24:58,386 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
16:24:58,476 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Pushing component [layout] on top of the object stack.
16:24:58,584 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
16:24:58,584 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
16:24:58,584 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
16:24:58,585 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
16:24:58,585 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]

Aug 23 16:24:59 - INFO  - Reflections took 195 ms to scan 2 urls, producing 67 keys and 164 values
Aug 23 16:24:59 - ERROR - Unable to load configuration (org.lsc.exception.LscConfigurationException: Configuration exception: null)
org.lsc.exception.LscConfigurationException: Configuration exception: null
        at org.lsc.configuration.JaxbXmlConfigurationHelper.getConfiguration(JaxbXmlConfigurationHelper.java:162) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.Configuration.setUp(Configuration.java:482) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.run(Launcher.java:194) [lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.launch(Launcher.java:158) [lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.main(Launcher.java:141) [lsc-core-2.1.4.jar:na]
Caused by: javax.xml.bind.UnmarshalException: null
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:512) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:209) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:175) ~[na:1.7.0_131]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) ~[na:1.7.0_131]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162) ~[na:1.7.0_131]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171) ~[na:1.7.0_131]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:189) ~[na:1.7.0_131]
        at org.lsc.configuration.JaxbXmlConfigurationHelper.getConfiguration(JaxbXmlConfigurationHelper.java:160) ~[lsc-core-2.1.4.jar:na]
        ... 4 common frames omitted
Caused by: org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'lsc'.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1900) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:740) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:570) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.startElement(ValidatingUnmarshaller.java:86) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:125) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:619) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3129) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:203) ~[na:1.7.0_131]
        ... 10 common frames omitted
Aug 23 16:24:59 - INFO  - Configuration validation failed !
#############################################

/usr/bin/lsc -f /etc/lsc -v

16:27:00,972 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:27:00,972 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/etc/lsc/openldap2ad/logback.xml]
16:27:00,974 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
16:27:00,974 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/etc/lsc/openldap2ad/logback.xml]
16:27:00,974 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/lib/lsc/lsc-core-2.1.4.jar!/logback.xml]
16:27:01,120 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:27:01,130 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:27:01,138 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
16:27:01,215 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Pushing component [layout] on top of the object stack.
16:27:01,372 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
16:27:01,372 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
16:27:01,372 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
16:27:01,372 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
16:27:01,373 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]

Aug 23 16:27:02 - INFO  - Reflections took 196 ms to scan 2 urls, producing 67 keys and 164 values
Aug 23 16:27:02 - INFO  - Logging configuration successfully loaded from /etc/lsc/logback.xml
Aug 23 16:27:02 - INFO  - LSC configuration successfully loaded from /etc/lsc/
Aug 23 16:27:02 - INFO  - Configuration and environment successfully checked !

**Comment by coudot** [comment]
The error is here:

> Caused by: org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'lsc'.
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198) ~[na:1.7.0_131]

Seems your lsc.xml is not well formatted.

**Comment by ccharkos33** [comment]
<?xml version="1.0" ?>
<lscxmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">
	<connections>
		<ldapConnection>
			<name>ad-src-conn</name>
			<url>ldaps://xxx.xxx.xxx.xxx:636/DC=xxxxx,DC=local</url>
			<username>CN=replica,OU=XXXXXX,OU=XXXXX,DC=XXX,DC=local</username>
			<password>xxxxxxx</password>
			<authentication>SIMPLE</authentication>
			<referral>IGNORE</referral>
			<derefAliases>NEVER</derefAliases>
			<version>VERSION_3</version>
			<pageSize>-1</pageSize>
			<factory>com.sun.jndi.ldap.LdapCtxFactory</factory>
			<tlsActivated>false</tlsActivated>
		</ldapConnection>
		<ldapConnection>
			<name>ldap-dst-conn</name>
			<url>ldap://localhost:389/dc=xxxx,dc=local</url>
			<username>cn=xxxxx,dc=XXX,dc=xxxxx</username>
			<password>xxxxxxxxxxxx</password>
			<authentication>SIMPLE</authentication>
			<referral>IGNORE</referral>
			<derefAliases>NEVER</derefAliases>
			<version>VERSION_3</version>
			<pageSize>-1</pageSize>
			<factory>com.sun.jndi.ldap.LdapCtxFactory</factory>
			<tlsActivated>false</tlsActivated>
		</ldapConnection>
	</connections>
	<tasks>
		<task>
			<name>People</name>
			<bean>org.lsc.beans.SimpleBean</bean>
			<ldapSourceService>
				<name>ad-source-service</name>
				<connection reference="ad-src-conn" />
				<baseDn>DC=xxxxx,DC=local</baseDn>
				<pivotAttributes>
					<string>samAccountName</string>
				</pivotAttributes>
				<fetchedAttributes>
					<string>description</string>
					<string>cn</string>
					<string>sn</string>
					<string>givenName</string>
					<string>samAccountName</string>
					<string>userPrincipalName</string>
				</fetchedAttributes>
				<getAllFilter>(objectClass=user)</getAllFilter>
				<getOneFilter>(&amp;(objectClass=user)(samAccountName={samAccountName}))</getOneFilter>
				<cleanFilter>(&amp;(objectClass=user)(samAccountName={uid}))</cleanFilter>
			</ldapSourceService>
			<ldapDestinationService>
				<name>opends-dst-service</name>
				<connection reference="ldap-dst-conn" />
				<baseDn>ou=xxxxx,dc=xxxxx,dc=local</baseDn>
				<pivotAttributes>
					<string>uid</string>
				</pivotAttributes>
				<fetchedAttributes>
					<string>description</string>
					<string>cn</string>
					<string>sn</string>
					<string>userPassword</string>
					<string>objectClass</string>
					<string>uid</string>
					<string>mail</string>
				</fetchedAttributes>
				<getAllFilter>(objectClass=inetorgperson)</getAllFilter>
				<getOneFilter>(&amp;(objectClass=inetorgperson)(uid={samAccountName}))</getOneFilter>
			</ldapDestinationService>
			<propertiesBasedSyncOptions>
				<mainIdentifier>"uid=" +
					srcBean.getDatasetFirstValueById("samAccountName") +
					",ou=xxxx,dc=xxx,dc=local"</mainIdentifier>
				<mainIdentifier>"cn=" + srcBean.getDatasetFirstValueById("cn") + ",cn=Users,dc=lsc-project,dc=org"</mainIdentifier>
				<defaultDelimiter>;</defaultDelimiter>
				<defaultPolicy>FORCE</defaultPolicy>
				<dataset>
					<name>description</name>
					<policy>FORCE</policy>
					<forceValues>
						<string>js:(srcBean.getDatasetFirstValueById("sn") != null  ? srcBean.getDatasetFirstValueById("sn").toUpperCase() : null )</string>
					</forceValues>
				</dataset>
				<dataset>
					<name>userPassword</name>
					<policy>KEEP</policy>
					<createValues>
						<string>js:"{SASL}" +
							srcBean.getDatasetFirstValueById("userPrincipalName")</string>
					</createValues>
				</dataset>
				<dataset>
					<name>sn</name>
					<policy>FORCE</policy>
					<defaultValues>
						<string>js:(srcBean.getDatasetFirstValueById("sn") != null  ? srcBean.getDatasetFirstValueById("sn").toUpperCase() : srcBean.getDatasetFirstValueById("cn") )</string>
					</defaultValues>
				</dataset>
				<dataset>
					<name>description</name>
					<policy>FORCE</policy>
					<forceValues>
						<string>js:(srcBean.getDatasetFirstValueById("sn") != null  ? srcBean.getDatasetFirstValueById("sn").toUpperCase() : null )</string>
					</forceValues>
				</dataset>
				<dataset>
					<name>uid</name>
					<policy>KEEP</policy>
					<createValues>
						<string>js:srcBean.getDatasetFirstValueById("samAcccountName")</string>
					</createValues>
				</dataset>
				<dataset>
					<name>objectClass</name>
					<policy>KEEP</policy>
					<createValues>
						<string>"inetOrgPerson"</string>
					</createValues>
				</dataset>
				<dataset>
					<name>userPassword</name>
					<policy>KEEP</policy>
					<createValues>
						<string>"changethis"</string>
					</createValues>
				</dataset>
			</propertiesBasedSyncOptions>
		</task>
	</tasks>
</lsc>

**Comment by coudot** [comment]
You can see that a space is missing here after lsc word:
````xml
<lscxmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">
````

**Comment by ccharkos33** [comment]
Despite correction always the same problem

Aug 23 16:46:26 - ERROR - Unable to load configuration (org.lsc.exception.LscConfigurationException: Configuration exception: null)
org.lsc.exception.LscConfigurationException: Configuration exception: null
        at org.lsc.configuration.JaxbXmlConfigurationHelper.getConfiguration(JaxbXmlConfigurationHelper.java:162) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.Configuration.setUp(Configuration.java:482) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.run(Launcher.java:194) [lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.launch(Launcher.java:158) [lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.main(Launcher.java:141) [lsc-core-2.1.4.jar:na]
Caused by: javax.xml.bind.UnmarshalException: null
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:512) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:209) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:175) ~[na:1.7.0_131]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) ~[na:1.7.0_131]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162) ~[na:1.7.0_131]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171) ~[na:1.7.0_131]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:189) ~[na:1.7.0_131]
        at org.lsc.configuration.JaxbXmlConfigurationHelper.getConfiguration(JaxbXmlConfigurationHelper.java:160) ~[lsc-core-2.1.4.jar:na]
        ... 4 common frames omitted
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'mainIdentifier'. One of '{"http://lsc-project.org/XSD/lsc-core-2.1.xsd":defaultDelimiter}' is expected.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:452) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3230) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1790) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:740) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:570) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.startElement(ValidatingUnmarshaller.java:86) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:125) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[na:1.7.0_131]
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642) ~[na:1.7.0_131]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:203) ~[na:1.7.0_131]
        ... 10 common frames omitted

**Comment by coudot** [comment]
You now need to check error message:
> Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'mainIdentifier'. One of '{"http://lsc-project.org/XSD/lsc-core-2.1.xsd":defaultDelimiter}' is expected.

Work on your lsc.xml file to have a correct syntax. A lot of examples are available on LSC website.

**Comment by ccharkos33** [comment]
my problem is solved 

I used this example which is on your github

https://github.com/lsc-project/lsc/blob/master/sample/ad/etc-ad2opendj/lsc.xml

this the line is the problem : 

<mainIdentifier>"uid=" +
					srcBean.getDatasetFirstValueById("samAccountName") +
					",ou=xxxx,dc=xxx,dc=local"</mainIdentifier>

resolution : 

<mainIdentifier>"uid=" + srcBean.getDatasetFirstValueById("samAccountName") + 		",ou=xxxx,dc=xxx,dc=local"</mainIdentifier>


thank you very much

Clément

**Comment by coudot** [comment]
Indeed, seems a bad formatting action that has added line breaks.
