### ISSUE TITLE
Java 21: GraalJSEngineFactory could not be instantiated

### ISSUE THREAD

**Issue by xavierba** [lsc-project/lsc#280]
CI fails when using Java 21 with the following error:

```
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
Error:  Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.645 s <<< FAILURE! - in org.lsc.beans.syncoptions.PropertiesBasedSyncOptionsTest
Error:  org.lsc.beans.syncoptions.PropertiesBasedSyncOptionsTest.testJS  Time elapsed: 0.606 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "org.lsc.utils.ScriptableEvaluator.evalToObjectList(org.lsc.Task, String, java.util.Map)" because "se" is null
	at org.lsc.utils.ScriptingEvaluator.evalToObjectList(ScriptingEvaluator.java:159)
	at org.lsc.beans.syncoptions.PropertiesBasedSyncOptionsTest.testJS(PropertiesBasedSyncOptionsTest.java:164)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```

See https://github.com/lsc-project/lsc/actions/runs/8688835816/job/23825324318#step:10:155

**Comment by artlog** [comment]
@taking a look

**Comment by artlog** [comment]
This error happen on Adoptium (Temurin), debian or ubuntu are shipped with those.
It does not happen on RedHat or Fedora where a openjdk or derivative is provided.
In any case a NullPointerException is never acceptable.

**Comment by abpai94** [comment]
I think this might be the PR: #292

**Comment by davidcoutadeur** [comment]
Done in #304 and completed in #340
