### ISSUE TITLE
LSC fails on first duplicate entry when running in clean mode and using DataBase as source

### ISSUE THREAD

**Issue by coudot** [lsc-project/lsc#308]
We run a connector DB -> LDAP

In clean phase, we have a duplicate entry, and so LSC logs an error:
```
oct. 02 16:16:36 - ERROR - Error while synchronizing ID {uid=toto}: org.lsc.exception.LscServiceException: Only a single record can be returned from a getObject request ! For id=uid=toto,ou=users,dc=example,dc=com, there are 2 records !
```

This behavior is correct.

But just after we have:
```
oct. 02 16:16:36 - ERROR - java.lang.NullPointerException
```

We should instead switch to next entry and have an error in the final status:
```
oct. 02 16:15:50 - INFO  - All entries: 666, to modify entries: 1, successfully modified entries: 0, errors: 1
```

There should be something to catch in the databaseSourceService code

**Comment by elecharny** [comment]
A few questions:

- When you mean duplicate entry, you mean the DB returns 2 times the same entry (same ID, same values)?
- Do you have any info about the NPE (stack trace, file+line number)?.

**Comment by elecharny** [comment]
Can't get to the NPE:

```
11:30:36.410 [db2ldapSyncTestTask-70] DEBUG org.lsc.AbstractSynchronize - org.lsc.exception.LscServiceException: Only a single record can be returned from a getObject request ! For id=epereira@linagora.com, Pereira (9), there are 2 records !
org.lsc.exception.LscServiceException: Only a single record can be returned from a getObject request ! For id=epereira@linagora.com, Pereira (9), there are 2 records !
	at org.lsc.service.AbstractJdbcService.getBean(AbstractJdbcService.java:219)
	at org.lsc.AbstractSynchronize.getBean(AbstractSynchronize.java:428)
	at org.lsc.runnable.SynchronizeEntryRunner.run(SynchronizeEntryRunner.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
11:30:48.123 [main] ERROR org.lsc.AbstractSynchronize - db2ldapSyncTestTask - sync - All entries: 9, to modify entries: 7, successfully modified entries: 7, errors: 2
11:30:52.070 [main] INFO  org.lsc.jndi.JndiServices - Connecting to LDAP server ldap://localhost:33389/dc=lsc-project,dc=org as cn=Directory Manager,ou=system
...
```
