### ISSUE TITLE
async task connection reset after 15 minutes

### ISSUE THREAD

**Issue by liordot** [lsc-project/lsc#40]
Hi,

I am syncing data from Active Directory and it's working fine in sync
mode but when running in async mode I see the following error in the
log and the data is no longer being synced.

Feb 13 14:18:46 ip-10-0-135-60 sync[12163]: Feb 13 14:18:46 - DEBUG -
Asynchronous synchronize SyncUserTask
Feb 13 14:33:55 ip-10-0-135-60 sync[12163]: Feb 13 14:33:55 - WARN  -
Connection reset by peer
```
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_151]
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_151]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_151]
at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_151]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_151]
at org.apache.mina.transport.socket.nio.NioProcessor.read(NioProcessor.java:273) ~[mina-core-2.0.7.jar:na]
at org.apache.mina.transport.socket.nio.NioProcessor.read(NioProcessor.java:44) ~[mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:690) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124) [mina-core-2.0.7.jar:na]
at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [mina-core-2.0.7.jar:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```
Is the 15 minutes timeout can be configured on the LSC or AD side?
Is there some way to establish the connection again without restarting LSC?

Another thing that I've noticed is that once this exception happens
and I change something in the AD,I get this error:
```
ERROR - LDAP error while reading entry CN=Test User,OU=Users,OU=ad-testing,DC=ad-testing,DC=test,DC=io (org.apache.directory.ldap.client.api.exception.InvalidConnectionException: Cannot connect on the server, the connection is invalid)
DEBUG - org.apache.directory.ldap.client.api.exception.InvalidConnectionException: Cannot connect on the server, the connection is invalid
org.apache.directory.ldap.client.api.exception.InvalidConnectionException: Cannot connect on the server, the connection is invalid
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.checkSession(LdapNetworkConnection.java:271) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.searchAsync(LdapNetworkConnection.java:1667) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.search(LdapNetworkConnection.java:1710) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.search(LdapNetworkConnection.java:1603) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.search(LdapNetworkConnection.java:1613) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.lsc.service.SyncReplSourceService.getBean(SyncReplSourceService.java:250) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:689) [lsc-core-2.1.4.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```

**Comment by coudot** [comment]
The connection seems to be reset by the client. There can be a timeout configuration on AD side.

As answered by @soisik on the mailing list, async Source LDAP service is very limited with AD.

**Comment by liordot** [comment]
I understand the limitations of async connections with AD but it does work fine for the first 15 minutes.
If the connection is being reset on the client side, it means that the issue can be solved on the LSC side, no?

**Comment by coudot** [comment]
Yes, maybe the connection reset can be catched. @rouazana, @soisik, what do you think?

**Comment by soisik** [comment]
I've sent the pull request #42 to fix this issue ; LSC does reuse the same connection when applying changes and it doesn't check if the reused connection is still alive before reusing it, which can easily lead to connection timing out on server side (or network) if no changes are detected and applied for some time.
