### ISSUE TITLE
Validation custom lsc.xml report error "lsc-core-2.1.xsd":bean}' is expected."

### ISSUE THREAD

**Issue by lklkxcxc** [lsc-project/lsc#59]
LSC version: lsc-2.1.4-0
Run "/usr/bin/lsc -f /etc/lsc/openldap2ad -v" report next error,But check default lsc.xml is success:

> May 22 14:36:42 - ERROR - Unable to load configuration (org.lsc.exception.LscConfigurationException: Configuration exception: null)
org.lsc.exception.LscConfigurationException: Configuration exception: null
        at org.lsc.configuration.JaxbXmlConfigurationHelper.getConfiguration(JaxbXmlConfigurationHelper.java:162) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.Configuration.setUp(Configuration.java:482) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.run(Launcher.java:194) [lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.launch(Launcher.java:158) [lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.main(Launcher.java:141) [lsc-core-2.1.4.jar:na]
Caused by: javax.xml.bind.UnmarshalException: null
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335) ~[na:1.8.0_77]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563) ~[na:1.8.0_77]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249) ~[na:1.8.0_77]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214) ~[na:1.8.0_77]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) ~[na:1.8.0_77]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162) ~[na:1.8.0_77]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171) ~[na:1.8.0_77]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:189) ~[na:1.8.0_77]
        at org.lsc.configuration.JaxbXmlConfigurationHelper.getConfiguration(JaxbXmlConfigurationHelper.java:160) ~[lsc-core-2.1.4.jar:na]
        ... 4 common frames omitted
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'ldapSourceService'. One of '{"http://lsc-project.org/XSD/lsc-core-2.1.xsd":bean}' is expected.

My custom lsc.xml copy complete from this article “Populating Active Directory from OpenLDAP”[https://lsc-project.org/documentation/tutorial/openldaptoactivedirectory](url)

The attachment is my lsc.xml
[lsc.zip](https://github.com/lsc-project/lsc/files/2025255/lsc.zip)

**Comment by 1trbot1** [comment]
@lklkxcxc Hi,
I have same issue, did you figured out what was the cause of the error?
