### ISSUE TITLE
Problem using NIS source service plugins with java 8

### ISSUE THREAD

**Issue by soisik** [lsc-project/lsc#72]
Probably after other plugins.
Execution ends with following errors :

```
Oct 24 17:21:21 - ERROR - Unable to load configuration (org.lsc.exception.LscConfigurationException: Configuration exception: src-resolve: Cannot resolve the name 'lsc:connectionType' to a(n) 'type definition' component.)
org.lsc.exception.LscConfigurationException: Configuration exception: src-resolve: Cannot resolve the name 'lsc:connectionType' to a(n) 'type definition' component.
        at org.lsc.configuration.JaxbXmlConfigurationHelper.getConfiguration(JaxbXmlConfigurationHelper.java:157) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.Configuration.setUp(Configuration.java:482) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.run(Launcher.java:194) [lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.launch(Launcher.java:158) [lsc-core-2.1.4.jar:na]
        at org.lsc.Launcher.main(Launcher.java:141) [lsc-core-2.1.4.jar:na]
Caused by: org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'lsc:connectionType' to a(n) 'type definition' component.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4154) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4137) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1684) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexContent(XSDComplexTypeTraverser.java:768) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexTypeDecl(XSDComplexTypeTraverser.java:315) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseGlobal(XSDComplexTypeTraverser.java:191) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1436) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:635) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:610) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:569) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:535) ~[na:1.8.0_191]
        at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:254) ~[na:1.8.0_191]
        at org.lsc.configuration.JaxbXmlConfigurationHelper.getConfiguration(JaxbXmlConfigurationHelper.java:151) ~[lsc-core-2.1.4.jar:na]
        ... 4 common frames omitted
```

**Comment by rouazana** [comment]
Yes I guess other plugins are also concerned.

**Comment by coudot** [comment]
Maybe this issue should be opened here: https://github.com/lsc-project/lsc-nis-plugin

And similar issues in https://github.com/lsc-project/lsc-obm-plugin and https://github.com/lsc-project/lsc-executable-plugin if they are confirmed

**Comment by soisik** [comment]
I can move it if you want, but the problem is likely to be in lsc-core (src/main/java/org/lsc/configuration/JaxbXmlConfigurationHelper.java) and affect all plugins.

**Comment by coudot** [comment]
Ok in this case this is the right place

**Comment by rouazana** [comment]
Should be fixed by https://github.com/lsc-project/lsc/pull/91
