### ISSUE TITLE
LSC debian packages break on Debian Buster

### ISSUE THREAD

**Issue by mrvanes** [lsc-project/lsc#84]
We're exploring the possibilities to migrate to Debian Buster and one of the showstoppers is LSC not working on Buster:

```
Error: java.util.MissingResourceException: Can't find bundle for base name javax.xml.bind.Messages, locale en_US
java.util.MissingResourceException: Can't find bundle for base name javax.xml.bind.Messages, locale en_US
        at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857)
        at javax.xml.bind.Messages.format(Messages.java:36)
        at javax.xml.bind.Messages.format(Messages.java:21)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:151)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:299)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:372)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:337)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:244)
        at org.lsc.configuration.JaxbXmlConfigurationHelper.<init>(JaxbXmlConfigurationHelper.java:105)
        at org.lsc.Configuration.setUp(Configuration.java:482)
        at org.lsc.Launcher.run(Launcher.java:194)
        at org.lsc.Launcher.launch(Launcher.java:158)
        at org.lsc.Launcher.main(Launcher.java:141)
Caused by: java.lang.ClassCastException: javax.xml.bind.Messages cannot be cast to ResourceBundle
        at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3201)
        at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1994)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1776)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1662)
        ... 15 more
```
This is, using openjdk-11-jdk/jre but 12 and 13 are available as well.

**Comment by soisik** [comment]
Hi Martin,
LSC does not support JDKs over version 8. 
We are hoping to add support soon.

**Comment by coudot** [comment]
See also #33

**Comment by coudot** [comment]
Will be fixed in 2.2

**Comment by jauling** [comment]
> Hi Martin,
> LSC does not support JDKs over version 8.
> We are hoping to add support soon.

We're trying to get LSC working in Ubuntu 20.04, we've installed JDK 8, but also getting same message. 

```
# java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

**Comment by faust64** [comment]
Hi,

Is that a similar error you're seeing, regarding `javax.xml.bind.Messages` ? Otherwise could you share it with us?

I did manage to reproduce this, while mistakenly using JDK11.
After re-installing the proper JDK version, that trace is gone.

Could there be two versions of java installed on that server? Are you certain JDK8 is being used by LSC?
Can you show us your `/etc/default/lsc` -- might be a place to usually configure this.
Can you confirm there's only one JDK in `/usr/lib/jvm` ?

Regards.

**Comment by jauling** [comment]
Hi @faust64 
You are correct. I made a boo boo. It was the same exact error.

I haven't used the `update-alternatives --config java` command before, and I blindly assumed it set `JAVA_HOME`, amongst other things. That command seems to just make sure the `/usr/bin/java` symlink is set to the selected JDK. Not sure how this happened, but there was a hardcoded `JAVA_HOME` variable in my `.profile`, which was (for some reason) pointing at `/usr/lib/jvm/default-java/`, which was **not** JDK8. Looking at the `get_java()` function in `lsc`, I can confirm this is was the problem. I removed this entry, and lsc is working as designed. 

Apologies for the false alarm! JDK8 seems to work fine in Ubuntu 20.04 with `lsc`.

**Comment by faust64** [comment]
Good to know, thanks for following-up.

**Comment by mahnaz90** [comment]
> Hi @faust64 You are correct. I made a boo boo. It was the same exact error.
> 
> I haven't used the `update-alternatives --config java` command before, and I blindly assumed it set `JAVA_HOME`, amongst other things. That command seems to just make sure the `/usr/bin/java` symlink is set to the selected JDK. Not sure how this happened, but there was a hardcoded `JAVA_HOME` variable in my `.profile`, which was (for some reason) pointing at `/usr/lib/jvm/default-java/`, which was **not** JDK8. Looking at the `get_java()` function in `lsc`, I can confirm this is was the problem. I removed this entry, and lsc is working as designed.
> 
> Apologies for the false alarm! JDK8 seems to work fine in Ubuntu 20.04 with `lsc`.

Hi Jauling 
you removed JAVA_HOME from /usr/lib/lsc? and what do replace ?
